### ISSUE TITLE
Scalling is way Off

### ISSUE THREAD

**Issue by KSaiAkshit** [SolDoesTech/HyprV2#2]
I ran the script and when i log back into Hyprland, everything is massive. The scale is way off. I tried changing the `monitor` tag in the `hyprland.conf` but to no use. I would love to provide a screenshot but spectacle doesn't work for some reason.

I use EndeavourOS, with the zen kernel `6.2.9-zen1-1-zen`.

**Comment by DasIschBims** [comment]
Fixing your monitors in the hyprland config should work, might be the scale.
Would recommend just checking the [Hyprland wiki](https://wiki.hyprland.org/Configuring/Monitors/)

**Comment by kevinwaxi** [comment]
Try changing the values from auto to actual calling numbers

**Comment by KSaiAkshit** [comment]
> Try changing the values from auto to actual calling numbers

Yeah, this worked!
Thanks for the help!
